/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qrPZwqtrqWM4S9b4djCj1H
// Component: j_koFSvK1RER

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import { _useGlobalVariants } from "../proliga_v_4/plasmic"; // plasmic-import: qrPZwqtrqWM4S9b4djCj1H/projectModule
import { _useStyleTokens } from "../proliga_v_4/PlasmicStyleTokensProvider"; // plasmic-import: qrPZwqtrqWM4S9b4djCj1H/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicNavbar.module.css"; // plasmic-import: j_koFSvK1RER/css

import Icon5Icon from "../proliga_v_4/icons/PlasmicIcon__Icon5"; // plasmic-import: NXdWphelV7Ee/icon
import Icon4Icon from "../proliga_v_4/icons/PlasmicIcon__Icon4"; // plasmic-import: D1ZJUrIo0Osa/icon

createPlasmicElementProxy;

export type PlasmicNavbar__VariantMembers = {};
export type PlasmicNavbar__VariantsArgs = {};
type VariantPropType = keyof PlasmicNavbar__VariantsArgs;
export const PlasmicNavbar__VariantProps = new Array<VariantPropType>();

export type PlasmicNavbar__ArgsType = { onUserChange?: (val: string) => void };
type ArgPropType = keyof PlasmicNavbar__ArgsType;
export const PlasmicNavbar__ArgProps = new Array<ArgPropType>("onUserChange");

export type PlasmicNavbar__OverridesType = {
  root?: Flex__<"div">;
  mainStack?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  items?: Flex__<"div">;
  competition?: Flex__<"div">;
  userMenuContainer?: Flex__<"div">;
  notificationBell?: Flex__<"svg">;
  userMenu?: Flex__<"div">;
  userImage?: Flex__<"div">;
  arrowDown2?: Flex__<"svg">;
};

export interface DefaultNavbarProps {
  onUserChange?: (val: string) => void;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavbar__RenderFunc(props: {
  variants: PlasmicNavbar__VariantsArgs;
  args: PlasmicNavbar__ArgsType;
  overrides: PlasmicNavbar__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "user",
        type: "readonly",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ({
          access_token: "",
          token_type: "",
          expires_in: 0,
          expires_at: 0,
          refresh_token: "",
          user: {
            id: "",
            aud: "",
            role: "",
            email: "",
            email_confirmed_at: "",
            phone: "",
            confirmed_at: "",
            recovery_sent_at: "",
            reauthentication_sent_at: "",
            last_sign_in_at: "",
            app_metadata: { provider: "", providers: [] },
            user_metadata: {
              email: "",
              email_verified: false,
              phone_verified: false,
              sub: ""
            },
            identities: [],
            created_at: "",
            updated_at: "",
            is_anonymous: false
          }
        }),

        onChangeProp: "onUserChange"
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_qrPZwqtrqWM4S9b4djCj1H",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"mainStack"}
        data-plasmic-override={overrides.mainStack}
        className={classNames("all", sty.mainStack)}
      >
        <PlasmicImg__
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"180px"}
          loading={"lazy"}
          onClick={async event => {
            const $steps = {};

            $steps["goToHomepage"] = true
              ? (() => {
                  const actionArgs = { destination: `/` };
                  return (({ destination }) => {
                    if (
                      typeof destination === "string" &&
                      destination.startsWith("#")
                    ) {
                      document
                        .getElementById(destination.substr(1))
                        .scrollIntoView({ behavior: "smooth" });
                    } else {
                      __nextRouter?.push(destination);
                    }
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["goToHomepage"] != null &&
              typeof $steps["goToHomepage"] === "object" &&
              typeof $steps["goToHomepage"].then === "function"
            ) {
              $steps["goToHomepage"] = await $steps["goToHomepage"];
            }
          }}
          src={{
            src: "/plasmic/copy_of_proliga_new_design/images/photo20240724145023RemovebgPreviewJpg.jpg",
            fullWidth: 1148,
            fullHeight: 217,
            aspectRatio: undefined
          }}
        />

        <div
          data-plasmic-name={"items"}
          data-plasmic-override={overrides.items}
          className={classNames("all", sty.items)}
        >
          <Reveal
            cascade={false}
            className={classNames("__wab_instance", sty.reveal__r92BL)}
            effect={"fade"}
            reverse={false}
            triggerOnce={false}
          >
            <div
              className={classNames("all", "__wab_text", sty.text___4DInn)}
              onClick={async event => {
                const $steps = {};

                $steps["goToMatches"] = true
                  ? (() => {
                      const actionArgs = { destination: `/matches` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToMatches"] != null &&
                  typeof $steps["goToMatches"] === "object" &&
                  typeof $steps["goToMatches"].then === "function"
                ) {
                  $steps["goToMatches"] = await $steps["goToMatches"];
                }
              }}
            >
              <React.Fragment>
                <span
                  className={
                    "plasmic_default__all plasmic_default__span plasmic_default__span__qrPZw"
                  }
                  style={{ color: "#FFFFFF" }}
                >
                  {"O'yinlar"}
                </span>
              </React.Fragment>
            </div>
          </Reveal>
          <Reveal
            className={classNames("__wab_instance", sty.reveal__jar5)}
            triggerOnce={true}
          >
            <div
              className={classNames("all", "__wab_text", sty.text___1TxI5)}
              onClick={async event => {
                const $steps = {};

                $steps["goToMarkets"] = true
                  ? (() => {
                      const actionArgs = { destination: `/markets` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToMarkets"] != null &&
                  typeof $steps["goToMarkets"] === "object" &&
                  typeof $steps["goToMarkets"].then === "function"
                ) {
                  $steps["goToMarkets"] = await $steps["goToMarkets"];
                }
              }}
            >
              <React.Fragment>
                <span
                  className={
                    "plasmic_default__all plasmic_default__span plasmic_default__span__qrPZw"
                  }
                  style={{ color: "#FFFFFF" }}
                >
                  {"Yutuqlar"}
                </span>
              </React.Fragment>
            </div>
          </Reveal>
          <Reveal
            className={classNames("__wab_instance", sty.reveal__dZw4)}
            triggerOnce={true}
          >
            <div
              className={classNames("all", "__wab_text", sty.text__mh979)}
              onClick={async event => {
                const $steps = {};

                $steps["goToRankings"] = true
                  ? (() => {
                      const actionArgs = { destination: `/rankings` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToRankings"] != null &&
                  typeof $steps["goToRankings"] === "object" &&
                  typeof $steps["goToRankings"].then === "function"
                ) {
                  $steps["goToRankings"] = await $steps["goToRankings"];
                }
              }}
            >
              <React.Fragment>
                <span
                  className={
                    "plasmic_default__all plasmic_default__span plasmic_default__span__qrPZw"
                  }
                  style={{ color: "#FFFFFF" }}
                >
                  {"Qoidalar"}
                </span>
              </React.Fragment>
            </div>
          </Reveal>
          <Reveal
            className={classNames("__wab_instance", sty.reveal__zHeFt)}
            triggerOnce={true}
          >
            {(() => {
              try {
                return currentUser.isLoggedIn;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"competition"}
                data-plasmic-override={overrides.competition}
                className={classNames("all", "__wab_text", sty.competition)}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToChampionships"] = true
                    ? (() => {
                        const actionArgs = { destination: `/competition` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToChampionships"] != null &&
                    typeof $steps["goToChampionships"] === "object" &&
                    typeof $steps["goToChampionships"].then === "function"
                  ) {
                    $steps["goToChampionships"] =
                      await $steps["goToChampionships"];
                  }
                }}
              >
                <React.Fragment>
                  <span
                    className={
                      "plasmic_default__all plasmic_default__span plasmic_default__span__qrPZw"
                    }
                    style={{ color: "#FFFFFF" }}
                  >
                    {"Chempionatlar"}
                  </span>
                </React.Fragment>
              </div>
            ) : null}
          </Reveal>
        </div>
        <div
          data-plasmic-name={"userMenuContainer"}
          data-plasmic-override={overrides.userMenuContainer}
          className={classNames("all", sty.userMenuContainer)}
        >
          <Icon5Icon
            data-plasmic-name={"notificationBell"}
            data-plasmic-override={overrides.notificationBell}
            className={classNames("all", sty.notificationBell)}
            role={"img"}
          />

          <div
            data-plasmic-name={"userMenu"}
            data-plasmic-override={overrides.userMenu}
            className={classNames("all", sty.userMenu)}
          >
            <div
              data-plasmic-name={"userImage"}
              data-plasmic-override={overrides.userImage}
              className={classNames("all", sty.userImage)}
            />

            <Icon4Icon
              data-plasmic-name={"arrowDown2"}
              data-plasmic-override={overrides.arrowDown2}
              className={classNames("all", sty.arrowDown2)}
              role={"img"}
            />
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "mainStack",
    "img",
    "items",
    "competition",
    "userMenuContainer",
    "notificationBell",
    "userMenu",
    "userImage",
    "arrowDown2"
  ],
  mainStack: [
    "mainStack",
    "img",
    "items",
    "competition",
    "userMenuContainer",
    "notificationBell",
    "userMenu",
    "userImage",
    "arrowDown2"
  ],
  img: ["img"],
  items: ["items", "competition"],
  competition: ["competition"],
  userMenuContainer: [
    "userMenuContainer",
    "notificationBell",
    "userMenu",
    "userImage",
    "arrowDown2"
  ],
  notificationBell: ["notificationBell"],
  userMenu: ["userMenu", "userImage", "arrowDown2"],
  userImage: ["userImage"],
  arrowDown2: ["arrowDown2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  mainStack: "div";
  img: typeof PlasmicImg__;
  items: "div";
  competition: "div";
  userMenuContainer: "div";
  notificationBell: "svg";
  userMenu: "div";
  userImage: "div";
  arrowDown2: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavbar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavbar__VariantsArgs;
    args?: PlasmicNavbar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNavbar__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNavbar__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavbar__ArgProps,
          internalVariantPropNames: PlasmicNavbar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavbar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavbar";
  } else {
    func.displayName = `PlasmicNavbar.${nodeName}`;
  }
  return func;
}

export const PlasmicNavbar = Object.assign(
  // Top-level PlasmicNavbar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mainStack: makeNodeComponent("mainStack"),
    img: makeNodeComponent("img"),
    items: makeNodeComponent("items"),
    competition: makeNodeComponent("competition"),
    userMenuContainer: makeNodeComponent("userMenuContainer"),
    notificationBell: makeNodeComponent("notificationBell"),
    userMenu: makeNodeComponent("userMenu"),
    userImage: makeNodeComponent("userImage"),
    arrowDown2: makeNodeComponent("arrowDown2"),

    // Metadata about props expected for PlasmicNavbar
    internalVariantProps: PlasmicNavbar__VariantProps,
    internalArgProps: PlasmicNavbar__ArgProps
  }
);

export default PlasmicNavbar;
/* prettier-ignore-end */
