/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qrPZwqtrqWM4S9b4djCj1H
// Component: 6He0p5VJ5Omi

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import Logout from "../../Logout"; // plasmic-import: sncfOMCbdWMu/component
import TextInput from "../../TextInput"; // plasmic-import: 1UJD2btGUkCV/component
import { _useGlobalVariants } from "../proliga_v_4/plasmic"; // plasmic-import: qrPZwqtrqWM4S9b4djCj1H/projectModule
import { _useStyleTokens } from "../proliga_v_4/PlasmicStyleTokensProvider"; // plasmic-import: qrPZwqtrqWM4S9b4djCj1H/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicHomePageAdmin.module.css"; // plasmic-import: 6He0p5VJ5Omi/css

import SearchSvgIcon from "./icons/PlasmicIcon__SearchSvg"; // plasmic-import: DJCZ30FSSW4V/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: wUfM8ozzkHkf/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHomePageAdmin__VariantMembers = {};
export type PlasmicHomePageAdmin__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomePageAdmin__VariantsArgs;
export const PlasmicHomePageAdmin__VariantProps = new Array<VariantPropType>();

export type PlasmicHomePageAdmin__ArgsType = {};
type ArgPropType = keyof PlasmicHomePageAdmin__ArgsType;
export const PlasmicHomePageAdmin__ArgProps = new Array<ArgPropType>();

export type PlasmicHomePageAdmin__OverridesType = {
  root?: Flex__<"div">;
  logout?: Flex__<typeof Logout>;
  textInput?: Flex__<typeof TextInput>;
  textInput2?: Flex__<typeof TextInput>;
  textInput3?: Flex__<typeof TextInput>;
  mainAction?: Flex__<"div">;
  actions?: Flex__<"div">;
  players?: Flex__<"div">;
};

export interface DefaultHomePageAdminProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomePageAdmin__RenderFunc(props: {
  variants: PlasmicHomePageAdmin__VariantsArgs;
  args: PlasmicHomePageAdmin__ArgsType;
  overrides: PlasmicHomePageAdmin__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "textInput2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "textInput3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_qrPZwqtrqWM4S9b4djCj1H",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames("all", "__wab_text", sty.text__kn6RO)}>
            {"Calculation"}
          </div>
          <div className={classNames("all", sty.freeBox___38QKw)}>
            <Logout
              data-plasmic-name={"logout"}
              data-plasmic-override={overrides.logout}
              className={classNames("__wab_instance", sty.logout)}
            />
          </div>
          <div className={classNames("all", sty.freeBox__ldfrM)}>
            <div className={classNames("all", sty.freeBox__cnDtm)}>
              <div className={classNames("all", "__wab_text", sty.text__iuEr)}>
                {"CHEMPIONAT"}
              </div>
              <div className={classNames("all", "__wab_text", sty.text__hnRy2)}>
                {"KLUB"}
              </div>
              <div className={classNames("all", "__wab_text", sty.text__xZrR)}>
                {"POZITSIYA"}
              </div>
            </div>
          </div>
          <div className={classNames("all", sty.freeBox__jS6Nt)}>
            <TextInput
              data-plasmic-name={"textInput"}
              data-plasmic-override={overrides.textInput}
              className={classNames("__wab_instance", sty.textInput)}
              onChange={async (...eventArgs: any) => {
                ((...eventArgs) => {
                  generateStateOnChangeProp($state, ["textInput", "value"])(
                    (e => e.target?.value).apply(null, eventArgs)
                  );
                }).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Chempionat sort"}
              showEndIcon={true}
              value={
                generateStateValueProp($state, ["textInput", "value"]) ?? ""
              }
            />

            <TextInput
              data-plasmic-name={"textInput2"}
              data-plasmic-override={overrides.textInput2}
              className={classNames("__wab_instance", sty.textInput2)}
              onChange={async (...eventArgs: any) => {
                ((...eventArgs) => {
                  generateStateOnChangeProp($state, ["textInput2", "value"])(
                    (e => e.target?.value).apply(null, eventArgs)
                  );
                }).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Klub sort"}
              value={
                generateStateValueProp($state, ["textInput2", "value"]) ?? ""
              }
            />

            <TextInput
              data-plasmic-name={"textInput3"}
              data-plasmic-override={overrides.textInput3}
              className={classNames("__wab_instance", sty.textInput3)}
              onChange={async (...eventArgs: any) => {
                ((...eventArgs) => {
                  generateStateOnChangeProp($state, ["textInput3", "value"])(
                    (e => e.target?.value).apply(null, eventArgs)
                  );
                }).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Pozitsiya sort"}
              value={
                generateStateValueProp($state, ["textInput3", "value"]) ?? ""
              }
            />
          </div>
          <div
            data-plasmic-name={"mainAction"}
            data-plasmic-override={overrides.mainAction}
            className={classNames("all", sty.mainAction)}
          >
            <div
              data-plasmic-name={"actions"}
              data-plasmic-override={overrides.actions}
              className={classNames("all", sty.actions)}
            >
              <div className={classNames("all", sty.freeBox__jxUrv)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__fojVb)}
                >
                  {"Footbals"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__de2I5)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__fxCZu)}
                >
                  {"MInut"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__iLonf)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__m4Bp)}
                >
                  {"Gol"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__lm18J)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__tbQpb)}
                >
                  {"Assist"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__o6Hny)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__xhG9O)}
                >
                  {"Empty game"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox___241PO)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__ukG52)}
                >
                  {"No penalty"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__lUzgO)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__dVrei)}
                >
                  {"-2 Gol"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__zKjH)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__hwnby)}
                >
                  {"Yellow card"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__zfg1Z)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__dEDbj)}
                >
                  {"Red card"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__gNfi5)}>
                <div
                  className={classNames("all", "__wab_text", sty.text___6Uy8F)}
                >
                  {"Total"}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"players"}
              data-plasmic-override={overrides.players}
              className={classNames("all", sty.players)}
            >
              <div className={classNames("all", sty.freeBox__ajHz)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__ksd8)}
                >
                  {"Ronaldo"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__ctM0)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__pzFoX)}
                >
                  {"50"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__cRkv)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__k5ZW)}
                >
                  {"2"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__dXbS4)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__hc3Mv)}
                >
                  {"1"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox___8L8Dm)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__lNdjr)}
                >
                  {"0"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__ioilg)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__ozdP6)}
                >
                  {"0"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__crHg)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__ho6C)}
                >
                  {"0"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__tPv8N)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__yrDy)}
                >
                  {"2"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox___8SbNx)}>
                <div
                  className={classNames("all", "__wab_text", sty.text___3Zz3W)}
                >
                  {"1"}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__zoLki)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__tVj3X)}
                >
                  {"11"}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "logout",
    "textInput",
    "textInput2",
    "textInput3",
    "mainAction",
    "actions",
    "players"
  ],
  logout: ["logout"],
  textInput: ["textInput"],
  textInput2: ["textInput2"],
  textInput3: ["textInput3"],
  mainAction: ["mainAction", "actions", "players"],
  actions: ["actions"],
  players: ["players"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  logout: typeof Logout;
  textInput: typeof TextInput;
  textInput2: typeof TextInput;
  textInput3: typeof TextInput;
  mainAction: "div";
  actions: "div";
  players: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomePageAdmin__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomePageAdmin__VariantsArgs;
    args?: PlasmicHomePageAdmin__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomePageAdmin__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomePageAdmin__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomePageAdmin__ArgProps,
          internalVariantPropNames: PlasmicHomePageAdmin__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomePageAdmin__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomePageAdmin";
  } else {
    func.displayName = `PlasmicHomePageAdmin.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const PageGuard: React.FC<P> = props => (
    <PlasmicPageGuard__
      minRole={"ead2b235-73a3-4579-b15a-7fc91fc1a23a"}
      appId={"qrPZwqtrqWM4S9b4djCj1H"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={false}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

export const PlasmicHomePageAdmin = Object.assign(
  // Top-level PlasmicHomePageAdmin renders the root element
  withPlasmicPageGuard(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    logout: makeNodeComponent("logout"),
    textInput: makeNodeComponent("textInput"),
    textInput2: makeNodeComponent("textInput2"),
    textInput3: makeNodeComponent("textInput3"),
    mainAction: makeNodeComponent("mainAction"),
    actions: makeNodeComponent("actions"),
    players: makeNodeComponent("players"),

    // Metadata about props expected for PlasmicHomePageAdmin
    internalVariantProps: PlasmicHomePageAdmin__VariantProps,
    internalArgProps: PlasmicHomePageAdmin__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/home-page-admin",
      pagePath: "/home-page-admin",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomePageAdmin;
/* prettier-ignore-end */
