/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qrPZwqtrqWM4S9b4djCj1H
// Component: pm7y5M1MPq4e

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import Navbar from "../../Navbar"; // plasmic-import: j_koFSvK1RER/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "../proliga_v_4/plasmic"; // plasmic-import: qrPZwqtrqWM4S9b4djCj1H/projectModule
import { _useStyleTokens } from "../proliga_v_4/PlasmicStyleTokensProvider"; // plasmic-import: qrPZwqtrqWM4S9b4djCj1H/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicMatches.module.css"; // plasmic-import: pm7y5M1MPq4e/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "matches",

    openGraph: {
      title: "matches"
    },
    twitter: {
      card: "summary" as const,
      title: "matches"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicMatches__VariantMembers = {};
export type PlasmicMatches__VariantsArgs = {};
type VariantPropType = keyof PlasmicMatches__VariantsArgs;
export const PlasmicMatches__VariantProps = new Array<VariantPropType>();

export type PlasmicMatches__ArgsType = {};
type ArgPropType = keyof PlasmicMatches__ArgsType;
export const PlasmicMatches__ArgProps = new Array<ArgPropType>();

export type PlasmicMatches__OverridesType = {
  root?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  h2?: Flex__<"h2">;
  mainStak?: Flex__<"div">;
  leftStack?: Flex__<"div">;
  matchStak?: Flex__<"div">;
  rightStack?: Flex__<"div">;
  matchStak2?: Flex__<"div">;
};

export interface DefaultMatchesProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMatches__RenderFunc(props: {
  variants: PlasmicMatches__VariantsArgs;
  args: PlasmicMatches__ArgsType;
  overrides: PlasmicMatches__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "navbar.user",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $q: {},
    $refs
  });

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    matches: usePlasmicDataOp(() => {
      return {
        sourceId: "egnTD9CG9tqC7cm6ya647K",
        opId: "f3483166-d70c-438c-9ee9-c60fd4efdc80",
        userArgs: {},
        cacheKey: `plasmic.$.f3483166-d70c-438c-9ee9-c60fd4efdc80.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_qrPZwqtrqWM4S9b4djCj1H",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
            onUserChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["navbar", "user"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          />

          <div className={classNames("all", sty.freeBox__fWeOt)}>
            <div className={classNames("all", sty.freeBox__qRz4G)}>
              <div className={classNames("all", "__wab_text", sty.text__rdXwn)}>
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h2
                      data-plasmic-name={"h2"}
                      data-plasmic-override={overrides.h2}
                      className={classNames(
                        "all",
                        "h2",
                        "h2__qrPZw",
                        "__wab_text",
                        sty.h2
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span plasmic_default__span__qrPZw"
                          }
                          style={{ color: "#FFFFFF" }}
                        >
                          {"Matches"}
                        </span>
                      </React.Fragment>
                    </h2>
                  }
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"mainStak"}
            data-plasmic-override={overrides.mainStak}
            className={classNames("all", sty.mainStak)}
          >
            <div
              data-plasmic-name={"leftStack"}
              data-plasmic-override={overrides.leftStack}
              className={classNames("all", sty.leftStack)}
            >
              <div className={classNames("all", "__wab_text", sty.text__g4J0V)}>
                {"Today's Matches"}
              </div>
              <div
                data-plasmic-name={"matchStak"}
                data-plasmic-override={overrides.matchStak}
                className={classNames("all", sty.matchStak)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__fdGls)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={``}
                  loading={"lazy"}
                  src={
                    "https://assets-fantasy.llt-services.com/teambadge/t186/color/t186_real-madrid.png"
                  }
                  width={
                    hasVariant(globalVariants, "screen", "portrait")
                      ? "15px"
                      : "30px"
                  }
                />

                <div
                  className={classNames("all", "__wab_text", sty.text__oLcUb)}
                >
                  {"Real Madrid"}
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__r8Rgd)}
                >
                  {"7:0"}
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__vxAqZ)}
                >
                  {"Barcelona"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__mtsjI)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://assets-fantasy.llt-services.com/teambadge/t178/color/t178_fc-barcelona.png"
                  }
                  width={
                    hasVariant(globalVariants, "screen", "portrait")
                      ? "15px"
                      : "30px"
                  }
                />
              </div>
            </div>
            <div
              data-plasmic-name={"rightStack"}
              data-plasmic-override={overrides.rightStack}
              className={classNames("all", sty.rightStack)}
            >
              <div className={classNames("all", "__wab_text", sty.text__ccgMc)}>
                {"All Planning Matches"}
              </div>
              <div
                data-plasmic-name={"matchStak2"}
                data-plasmic-override={overrides.matchStak2}
                className={classNames("all", sty.matchStak2)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__n2HKf)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={``}
                  loading={"lazy"}
                  src={
                    "https://assets-fantasy.llt-services.com/teambadge/t186/color/t186_real-madrid.png"
                  }
                  width={
                    hasVariant(globalVariants, "screen", "portrait")
                      ? "15px"
                      : "30px"
                  }
                />

                <div
                  className={classNames("all", "__wab_text", sty.text__wOi6O)}
                >
                  {"Real Madrid"}
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__qjAz)}
                >
                  {"7:0"}
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__mu2G)}
                >
                  {"Barcelona"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___1Brix)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={
                    "https://assets-fantasy.llt-services.com/teambadge/t178/color/t178_fc-barcelona.png"
                  }
                  width={
                    hasVariant(globalVariants, "screen", "portrait")
                      ? "15px"
                      : "30px"
                  }
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "h2",
    "mainStak",
    "leftStack",
    "matchStak",
    "rightStack",
    "matchStak2"
  ],
  navbar: ["navbar"],
  h2: ["h2"],
  mainStak: ["mainStak", "leftStack", "matchStak", "rightStack", "matchStak2"],
  leftStack: ["leftStack", "matchStak"],
  matchStak: ["matchStak"],
  rightStack: ["rightStack", "matchStak2"],
  matchStak2: ["matchStak2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  h2: "h2";
  mainStak: "div";
  leftStack: "div";
  matchStak: "div";
  rightStack: "div";
  matchStak2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMatches__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMatches__VariantsArgs;
    args?: PlasmicMatches__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicMatches__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicMatches__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMatches__ArgProps,
          internalVariantPropNames: PlasmicMatches__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMatches__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMatches";
  } else {
    func.displayName = `PlasmicMatches.${nodeName}`;
  }
  return func;
}

export const PlasmicMatches = Object.assign(
  // Top-level PlasmicMatches renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    h2: makeNodeComponent("h2"),
    mainStak: makeNodeComponent("mainStak"),
    leftStack: makeNodeComponent("leftStack"),
    matchStak: makeNodeComponent("matchStak"),
    rightStack: makeNodeComponent("rightStack"),
    matchStak2: makeNodeComponent("matchStak2"),

    // Metadata about props expected for PlasmicMatches
    internalVariantProps: PlasmicMatches__VariantProps,
    internalArgProps: PlasmicMatches__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/matches",
      pagePath: "/matches",
      params: {},
      query: {}
    })
  }
);

export default PlasmicMatches;
/* prettier-ignore-end */
