/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qrPZwqtrqWM4S9b4djCj1H
// Component: maGCetjbMwYp

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import TextInput from "../../TextInput"; // plasmic-import: 1UJD2btGUkCV/component
import Button from "../../Button"; // plasmic-import: JtHKLkRqLyx-/component
import { _useGlobalVariants } from "../proliga_v_4/plasmic"; // plasmic-import: qrPZwqtrqWM4S9b4djCj1H/projectModule
import { _useStyleTokens } from "../proliga_v_4/PlasmicStyleTokensProvider"; // plasmic-import: qrPZwqtrqWM4S9b4djCj1H/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicLoginAuth.module.css"; // plasmic-import: maGCetjbMwYp/css

import SearchSvgIcon from "./icons/PlasmicIcon__SearchSvg"; // plasmic-import: DJCZ30FSSW4V/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: wUfM8ozzkHkf/icon

createPlasmicElementProxy;

export type PlasmicLoginAuth__VariantMembers = {};
export type PlasmicLoginAuth__VariantsArgs = {};
type VariantPropType = keyof PlasmicLoginAuth__VariantsArgs;
export const PlasmicLoginAuth__VariantProps = new Array<VariantPropType>();

export type PlasmicLoginAuth__ArgsType = {};
type ArgPropType = keyof PlasmicLoginAuth__ArgsType;
export const PlasmicLoginAuth__ArgProps = new Array<ArgPropType>();

export type PlasmicLoginAuth__OverridesType = {
  root?: Flex__<"div">;
  columns?: Flex__<"div">;
  login?: Flex__<"div">;
  emailInput?: Flex__<typeof TextInput>;
  passwordInput?: Flex__<typeof TextInput>;
  submitButton?: Flex__<typeof Button>;
  nadpis?: Flex__<"div">;
};

export interface DefaultLoginAuthProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLoginAuth__RenderFunc(props: {
  variants: PlasmicLoginAuth__VariantsArgs;
  args: PlasmicLoginAuth__ArgsType;
  overrides: PlasmicLoginAuth__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "emailInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "passwordInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );

  const currentUser = useCurrentUser?.() || {};

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_qrPZwqtrqWM4S9b4djCj1H",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames("all", sty.freeBox__ajhj)}>
        <PlasmicImg__
          alt={""}
          className={classNames(sty.img__eywfF)}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"500px"}
          loading={"lazy"}
          src={
            "https://dlcdnwebimgs.asus.com/gain/3EF83AFB-7D9C-4D1A-918E-8910190606D1/fwebp"
          }
        />

        <div className={classNames("all", "__wab_text", sty.text__dWnOm)}>
          {"Biz bilan o'ynang va sovg'alar yutib oling!"}
        </div>
      </div>
      <div className={classNames("all", sty.freeBox___4UOhR)}>
        <div
          data-plasmic-name={"columns"}
          data-plasmic-override={overrides.columns}
          className={classNames("all", sty.columns)}
        >
          <div
            data-plasmic-name={"login"}
            data-plasmic-override={overrides.login}
            className={classNames("all", sty.login)}
          >
            <div className={classNames("all", "__wab_text", sty.text__dLz6J)}>
              {"Pochta"}
            </div>
            <TextInput
              data-plasmic-name={"emailInput"}
              data-plasmic-override={overrides.emailInput}
              className={classNames("__wab_instance", sty.emailInput)}
              onChange={async (...eventArgs: any) => {
                ((...eventArgs) => {
                  generateStateOnChangeProp($state, ["emailInput", "value"])(
                    (e => e.target?.value).apply(null, eventArgs)
                  );
                }).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Pochta"}
              required={true}
              value={
                generateStateValueProp($state, ["emailInput", "value"]) ?? ""
              }
            />

            <div className={classNames("all", "__wab_text", sty.text__jI7Ds)}>
              {"PAROL"}
            </div>
            <TextInput
              data-plasmic-name={"passwordInput"}
              data-plasmic-override={overrides.passwordInput}
              className={classNames("__wab_instance", sty.passwordInput)}
              onChange={async (...eventArgs: any) => {
                ((...eventArgs) => {
                  generateStateOnChangeProp($state, ["passwordInput", "value"])(
                    (e => e.target?.value).apply(null, eventArgs)
                  );
                }).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Parol"}
              required={true}
              type={"password"}
              value={
                generateStateValueProp($state, ["passwordInput", "value"]) ?? ""
              }
            />

            <Button
              data-plasmic-name={"submitButton"}
              data-plasmic-override={overrides.submitButton}
              className={classNames("__wab_instance", sty.submitButton)}
              color={"green"}
              onClick={async event => {
                const $steps = {};

                $steps["httpPost"] = true
                  ? (() => {
                      const actionArgs = {
                        dataOp: {
                          sourceId: "vQtRPuFArSfh43vUmgx2PS",
                          opId: "6ae21ca0-b0fe-416b-99a0-1cd5ec5eff8a",
                          userArgs: {
                            body: [
                              $state.emailInput.value,

                              $state.passwordInput.value
                            ]
                          },
                          cacheKey: null,
                          invalidatedKeys: ["plasmic_refresh_all"],
                          roleId: null
                        }
                      };
                      return (async ({ dataOp, continueOnError }) => {
                        try {
                          const response = await executePlasmicDataOp(dataOp, {
                            userAuthToken: dataSourcesCtx?.userAuthToken,
                            user: dataSourcesCtx?.user
                          });
                          await plasmicInvalidate(dataOp.invalidatedKeys);
                          return response;
                        } catch (e) {
                          if (!continueOnError) {
                            throw e;
                          }
                          return e;
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["httpPost"] != null &&
                  typeof $steps["httpPost"] === "object" &&
                  typeof $steps["httpPost"].then === "function"
                ) {
                  $steps["httpPost"] = await $steps["httpPost"];
                }

                $steps["updateEmailInputValue"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["emailInput", "value"]
                        },
                        operation: 0
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateEmailInputValue"] != null &&
                  typeof $steps["updateEmailInputValue"] === "object" &&
                  typeof $steps["updateEmailInputValue"].then === "function"
                ) {
                  $steps["updateEmailInputValue"] =
                    await $steps["updateEmailInputValue"];
                }
              }}
            >
              {"Kirish"}
            </Button>
            <div className={classNames("all", sty.freeBox__eTw3T)}>
              <div className={classNames("all", "__wab_text", sty.text__rYqBo)}>
                {"Don't you have an account "}
              </div>
              <div
                className={classNames("all", "__wab_text", sty.text___5JQ9P)}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToSignup"] = true
                    ? (() => {
                        const actionArgs = { destination: `/signup` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToSignup"] != null &&
                    typeof $steps["goToSignup"] === "object" &&
                    typeof $steps["goToSignup"].then === "function"
                  ) {
                    $steps["goToSignup"] = await $steps["goToSignup"];
                  }
                }}
              >
                {"Ro'yhatdan o'tish"}
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"nadpis"}
            data-plasmic-override={overrides.nadpis}
            className={classNames("all", sty.nadpis)}
          >
            <div className={classNames("all", "__wab_text", sty.text__bPj3J)}>
              {
                "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,\nmolestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum\nnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium\noptio, eaque rerum! Provident similique accusantium nemo autem. Veritatis\nobcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam"
              }
            </div>
            <div className={classNames("all", sty.freeBox__e0Ig)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__xvGRu)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={
                  "https://seeklogo.com/images/P/premier-league-new-logo-D22A0CE87E-seeklogo.com.png"
                }
                width={"150px"}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__kno9)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={
                  "https://seeklogo.com/images/P/premier-league-new-logo-D22A0CE87E-seeklogo.com.png"
                }
                width={"150px"}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__obOD)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={
                  "https://seeklogo.com/images/P/premier-league-new-logo-D22A0CE87E-seeklogo.com.png"
                }
                width={"150px"}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "columns",
    "login",
    "emailInput",
    "passwordInput",
    "submitButton",
    "nadpis"
  ],
  columns: [
    "columns",
    "login",
    "emailInput",
    "passwordInput",
    "submitButton",
    "nadpis"
  ],
  login: ["login", "emailInput", "passwordInput", "submitButton"],
  emailInput: ["emailInput"],
  passwordInput: ["passwordInput"],
  submitButton: ["submitButton"],
  nadpis: ["nadpis"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  columns: "div";
  login: "div";
  emailInput: typeof TextInput;
  passwordInput: typeof TextInput;
  submitButton: typeof Button;
  nadpis: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLoginAuth__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLoginAuth__VariantsArgs;
    args?: PlasmicLoginAuth__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLoginAuth__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLoginAuth__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLoginAuth__ArgProps,
          internalVariantPropNames: PlasmicLoginAuth__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLoginAuth__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLoginAuth";
  } else {
    func.displayName = `PlasmicLoginAuth.${nodeName}`;
  }
  return func;
}

export const PlasmicLoginAuth = Object.assign(
  // Top-level PlasmicLoginAuth renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),
    login: makeNodeComponent("login"),
    emailInput: makeNodeComponent("emailInput"),
    passwordInput: makeNodeComponent("passwordInput"),
    submitButton: makeNodeComponent("submitButton"),
    nadpis: makeNodeComponent("nadpis"),

    // Metadata about props expected for PlasmicLoginAuth
    internalVariantProps: PlasmicLoginAuth__VariantProps,
    internalArgProps: PlasmicLoginAuth__ArgProps
  }
);

export default PlasmicLoginAuth;
/* prettier-ignore-end */
