/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qrPZwqtrqWM4S9b4djCj1H
// Component: pZT07rlqywda

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qrPZwqtrqWM4S9b4djCj1H/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qrPZwqtrqWM4S9b4djCj1H/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../copy_of_proliga_new_design/plasmic.module.css"; // plasmic-import: qrPZwqtrqWM4S9b4djCj1H/projectcss
import sty from "./PlasmicNavbar2.module.css"; // plasmic-import: pZT07rlqywda/css

createPlasmicElementProxy;

export type PlasmicNavbar2__VariantMembers = {};
export type PlasmicNavbar2__VariantsArgs = {};
type VariantPropType = keyof PlasmicNavbar2__VariantsArgs;
export const PlasmicNavbar2__VariantProps = new Array<VariantPropType>();

export type PlasmicNavbar2__ArgsType = {};
type ArgPropType = keyof PlasmicNavbar2__ArgsType;
export const PlasmicNavbar2__ArgProps = new Array<ArgPropType>();

export type PlasmicNavbar2__OverridesType = {
  root?: Flex__<"div">;
  mainStack?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  logo?: Flex__<"div">;
  items?: Flex__<"div">;
  competition?: Flex__<"div">;
  login?: Flex__<"div">;
  freeBox?: Flex__<"div">;
};

export interface DefaultNavbar2Props {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavbar2__RenderFunc(props: {
  variants: PlasmicNavbar2__VariantsArgs;
  args: PlasmicNavbar2__ArgsType;
  overrides: PlasmicNavbar2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"mainStack"}
        data-plasmic-override={overrides.mainStack}
        className={classNames(projectcss.all, sty.mainStack)}
      >
        <PlasmicImg__
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"49px"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"230px"}
          loading={"lazy"}
          onClick={async event => {
            const $steps = {};

            $steps["goToHomepage"] = true
              ? (() => {
                  const actionArgs = { destination: `/` };
                  return (({ destination }) => {
                    if (
                      typeof destination === "string" &&
                      destination.startsWith("#")
                    ) {
                      document
                        .getElementById(destination.substr(1))
                        .scrollIntoView({ behavior: "smooth" });
                    } else {
                      __nextRouter?.push(destination);
                    }
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["goToHomepage"] != null &&
              typeof $steps["goToHomepage"] === "object" &&
              typeof $steps["goToHomepage"].then === "function"
            ) {
              $steps["goToHomepage"] = await $steps["goToHomepage"];
            }
          }}
          src={{
            src: "/plasmic/copy_of_proliga_new_design/images/photo20240724145023RemovebgPreviewJpg.jpg",
            fullWidth: 1148,
            fullHeight: 217,
            aspectRatio: undefined
          }}
        />

        <div
          data-plasmic-name={"logo"}
          data-plasmic-override={overrides.logo}
          className={classNames(projectcss.all, sty.logo)}
        >
          <Reveal
            children={null}
            className={classNames("__wab_instance", sty.reveal__mc1Yh)}
            triggerOnce={true}
          />
        </div>
        <div
          data-plasmic-name={"items"}
          data-plasmic-override={overrides.items}
          className={classNames(projectcss.all, sty.items)}
        >
          <Reveal
            cascade={false}
            className={classNames("__wab_instance", sty.reveal__etnVi)}
            effect={"fade"}
            reverse={false}
            triggerOnce={false}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__g8WO
              )}
              onClick={async event => {
                const $steps = {};

                $steps["goToMatches"] = true
                  ? (() => {
                      const actionArgs = { destination: `/matches` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToMatches"] != null &&
                  typeof $steps["goToMatches"] === "object" &&
                  typeof $steps["goToMatches"].then === "function"
                ) {
                  $steps["goToMatches"] = await $steps["goToMatches"];
                }
              }}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#FFFFFF" }}
                >
                  {"O'yinlar"}
                </span>
              </React.Fragment>
            </div>
          </Reveal>
          <Reveal
            className={classNames("__wab_instance", sty.reveal___9RlY)}
            triggerOnce={true}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__n1H5Z
              )}
              onClick={async event => {
                const $steps = {};

                $steps["goToMarkets"] = true
                  ? (() => {
                      const actionArgs = { destination: `/markets` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToMarkets"] != null &&
                  typeof $steps["goToMarkets"] === "object" &&
                  typeof $steps["goToMarkets"].then === "function"
                ) {
                  $steps["goToMarkets"] = await $steps["goToMarkets"];
                }
              }}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#FFFFFF" }}
                >
                  {"Yutuqlar"}
                </span>
              </React.Fragment>
            </div>
          </Reveal>
          <Reveal
            className={classNames("__wab_instance", sty.reveal___2Lt0V)}
            triggerOnce={true}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wJ90
              )}
              onClick={async event => {
                const $steps = {};

                $steps["goToRankings"] = true
                  ? (() => {
                      const actionArgs = { destination: `/rankings` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToRankings"] != null &&
                  typeof $steps["goToRankings"] === "object" &&
                  typeof $steps["goToRankings"].then === "function"
                ) {
                  $steps["goToRankings"] = await $steps["goToRankings"];
                }
              }}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#FFFFFF" }}
                >
                  {"Qoidalar"}
                </span>
              </React.Fragment>
            </div>
          </Reveal>
          <Reveal
            className={classNames("__wab_instance", sty.reveal__jidDk)}
            triggerOnce={true}
          >
            {(() => {
              try {
                return currentUser.isLoggedIn;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"competition"}
                data-plasmic-override={overrides.competition}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.competition
                )}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToChampionships"] = true
                    ? (() => {
                        const actionArgs = { destination: `/competition` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToChampionships"] != null &&
                    typeof $steps["goToChampionships"] === "object" &&
                    typeof $steps["goToChampionships"].then === "function"
                  ) {
                    $steps["goToChampionships"] =
                      await $steps["goToChampionships"];
                  }
                }}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#FFFFFF" }}
                  >
                    {"Chempionatlar"}
                  </span>
                </React.Fragment>
              </div>
            ) : null}
          </Reveal>
        </div>
        <div
          data-plasmic-name={"login"}
          data-plasmic-override={overrides.login}
          className={classNames(projectcss.all, sty.login)}
        >
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          />
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "mainStack",
    "img",
    "logo",
    "items",
    "competition",
    "login",
    "freeBox"
  ],
  mainStack: [
    "mainStack",
    "img",
    "logo",
    "items",
    "competition",
    "login",
    "freeBox"
  ],
  img: ["img"],
  logo: ["logo"],
  items: ["items", "competition"],
  competition: ["competition"],
  login: ["login", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  mainStack: "div";
  img: typeof PlasmicImg__;
  logo: "div";
  items: "div";
  competition: "div";
  login: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavbar2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavbar2__VariantsArgs;
    args?: PlasmicNavbar2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNavbar2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNavbar2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavbar2__ArgProps,
          internalVariantPropNames: PlasmicNavbar2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavbar2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavbar2";
  } else {
    func.displayName = `PlasmicNavbar2.${nodeName}`;
  }
  return func;
}

export const PlasmicNavbar2 = Object.assign(
  // Top-level PlasmicNavbar2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mainStack: makeNodeComponent("mainStack"),
    img: makeNodeComponent("img"),
    logo: makeNodeComponent("logo"),
    items: makeNodeComponent("items"),
    competition: makeNodeComponent("competition"),
    login: makeNodeComponent("login"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicNavbar2
    internalVariantProps: PlasmicNavbar2__VariantProps,
    internalArgProps: PlasmicNavbar2__ArgProps
  }
);

export default PlasmicNavbar2;
/* prettier-ignore-end */
