/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: q8iq2J191QypeBqVSHzb6M

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: q8iq2J191QypeBqVSHzb6M/projectModule

const data = {
  base: `${"plasmic_tokens_q8iq2J191QypeBqVSHzb6M"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
